#!/usr/bin/env python3
"""Rolls orders/, predictions/ and events.json up into data/agentic_insights.js for the Agentic Insights page.

The page loads this with a plain <script> tag (so it also works when index.html is opened from disk).
Run after generate_orders_predictions.py:   python3 data/build_agentic_page_data.py
"""
import json, os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ITEMS = [('burrito', 'Signature Burrito'), ('tacos', 'Street Tacos (3)'), ('bowl', 'Burrito Bowl'), ('nachos', 'Loaded Nachos'),
         ('quesadilla', 'Quesadilla'), ('chips-guac', 'Chips & Guac'), ('chips-queso', 'Chips & Queso'), ('salad', 'Taco Salad'),
         ('side-rice', 'Side of Rice'), ('side-beans', 'Side of Beans')]
TODAY = '2026-10-05'

def load(path):
    return json.load(open(os.path.join(HERE, path)))

def main():
    index = load('predictions/index.json')['days']
    events = defaultdict(list)
    for e in load('events.json'):
        events[e['date']].append(e)
    price = {}
    days = {}
    for row in index:
        d = row['date']
        p = load(f'predictions/{d}.json')
        hours = [int(h[:2]) for h in p['hours']]
        day = {
            'date': d, 'dow': p['day_of_week'], 'status': p['status'], 'open': p['open'], 'close': p['close'],
            'hours': hours,
            'baseline': p['baseline_items'], 'expected': p['expected_items'], 'range': p['range_items'], 'vs': p['expected_vs_baseline_pct'],
            'confidence': p['confidence'], 'peak': p['peak_hour'],
            'expHourly': p['hourly_expected'], 'expItems': p['hourly_expected_by_item'],
            'drivers': p['drivers'], 'prep': p['prep_notes'],
            'insight': p['agentic_insight'], 'actions': p['agentic_actions'], 'pending': p.get('agentic_pending'),
            'stat': p['statistical'], 'external': p['external'],
            'events': [{'name': e['name'], 'category': e['category'], 'venue': e['venue'], 'miles': e['distance_from_oracle_park_miles'],
                        'start': e['start_time'], 'end': e['estimated_end_time'], 'status': e['status'], 'placeholder': bool(e.get('placeholder'))}
                       for e in events.get(d, [])],
        }
        if d <= TODAY:
            o = load(f'orders/{d}.json')
            by = {i: [0] * len(hours) for i, _ in ITEMS}
            tot = [0] * len(hours)
            rows = defaultdict(lambda: {'qty': 0, 'revenue': 0.0, 'cost': 0.0})
            as_of = int(o['as_of'][:2]) if o['as_of'] else None
            for od in o['orders']:
                h = int(od['timestamp'][11:13])
                for it in od['items']:
                    price[it['menu_item_id']] = it['price']
                    if h in hours:
                        by[it['menu_item_id']][hours.index(h)] += 1
                        tot[hours.index(h)] += 1
                    r = rows[it['menu_item_id']]
                    r['qty'] += 1; r['revenue'] += it['price']; r['cost'] += it['ingredient_cost']
            if as_of is not None:             # hours that have not happened yet are null, not zero
                for k, h in enumerate(hours):
                    if h >= as_of:
                        tot[k] = None
                        for i in by: by[i][k] = None
            day['actHourly'], day['actItems'] = tot, by
            day['asOf'] = o['as_of']
            t = o['totals']
            day['totals'] = {'orders': t['orders'], 'items': t['items'], 'revenue': t['revenue'], 'cost': t['ingredient_cost']}
            day['actual'] = t['items']
            day['table'] = [{'id': i, 'name': n, 'qty': rows[i]['qty'], 'revenue': round(rows[i]['revenue'], 2), 'cost': round(rows[i]['cost'], 2)}
                            for i, n in ITEMS if rows[i]['qty']]
        days[d] = day
    for d, day in days.items():           # future days: an expected table (prices from the real sales)
        if day['status'] == 'future':
            p = load(f'predictions/{d}.json')
            rows = [{'id': i, 'name': n, 'qty': round(p['expected_items_by_item'][i]), 'revenue': round(p['expected_items_by_item'][i] * price[i], 2), 'cost': None}
                    for i, n in ITEMS]
            day['table'] = rows
            day['totals'] = {'orders': p['expected_orders'], 'items': round(p['expected_items']), 'revenue': p['expected_revenue'], 'cost': None}
    data = {'today': TODAY, 'items': [{'id': i, 'name': n} for i, n in ITEMS], 'days': days}
    out = os.path.join(HERE, 'agentic_insights.js')
    with open(out, 'w') as f:
        f.write('/* GENERATED by build_agentic_page_data.py: do not edit */\nwindow.AGENTIC_DATA=')
        json.dump(data, f, separators=(',', ':'), ensure_ascii=False)
        f.write(';\n')
    print(f'{len(days)} days, {os.path.getsize(out) // 1024} KB -> agentic_insights.js')

if __name__ == '__main__':
    main()
